import mongoose from 'mongoose';

const clinicSchema = new mongoose.Schema({
  generalDetails: {
    clinicName: { type: String, required: true },
    tagLine: String,
    ownerName: { type: String, required: true },
    website: String,
    advancedSecurity: { type: Boolean, default: false },
    logo1: String,
    logo2: String,
  },
  preferences: {
    calendarViewStart: String,
    calendarSlotDuration: String,
    appointmentDuration: String,
    calendarCardColor: String,
    topColor: String,
    changeAppointmentCard: Boolean,
    taskBackgroundColor: String,
    overdueTaskColor: String,
    taskFontColor: String,
    teethNoSystem: String,
    customPatientID: Boolean,
    activateAppointmentConfirmation: Boolean,
    newVisitorFrom: String,
    resetVoucherIdOnNewFinancialYear: Boolean,
    enableHeadCharting: Boolean,
  },
  patientRegistration: {
    mobile: String,
    email: String,
    dateOfBirth: String,
    localityCity: String,
    aadharCardNumber: String,
    nationality: String,
    sourceType: String,
    sourceCampaign: String,
  },
  printingSetup: {
    printPaper: String,
    letterheadPreference: String,
    letterheadSizePreference: String,
    leftMargin: String,
    topMargin: String,
    bottomMargin: String,
    rightMargin: String,
    fontSize: Number,
    medicalConditions: Boolean,
    allergies: Boolean,
    investigation: Boolean,
    diagnosis: Boolean,
    footers: {
      confirmation: String,
      advance: String,
      refund: String,
      creditNote: String,
      consent: String,
      consentShare: String,
      consentAmend: String,
      terms: String,
    },
  },
  patientPortalAccess: {
    showTreatments: Boolean,
    allowToEditProfile: Boolean,
    showTreatmentsCharges: Boolean,
    allowToEditMedicalConditions: Boolean,
    showFiles: Boolean,
  },
});

export default mongoose.model('Clinic', clinicSchema);